print("Esta es la primera practica"), print("probando codigo")
print("el", "uso", "de", "las", "comas")
print("8+3"), (8+3), print("hola \ncuco")
print("saludos \ndesde \npython\nesto es espacio\na\nb\nc\nd\ne\nf")
print("caracter de \tescape")
print("cuco\tescape")